--AGGREGATE FUNCTIONS (on MYSALARY table)

SELECT * FROM MYSALARY

SELECT AVG(SALARY) FROM MYSALARY

SELECT COUNT(*) FROM MYSALARY

SELECT COUNT(SALARY) FROM MYSALARY


--STRING FUNCTIONS

CREATE TABLE MYORDER(ORDERNUMBER INT, ORDERNAME VARCHAR(100), CUSTOMERID INT)
INSERT INTO MYORDER VALUES(1, 'ORDER1', 1)
INSERT INTO MYORDER VALUES(2, 'ORDER2', 2)
INSERT INTO MYORDER VALUES(3, 'ORDER3', 7)
INSERT INTO MYORDER VALUES(4, 'ORDER4', 8)

SELECT * FROM MYORDER

--CONCAT
PRINT CONCAT('String1','String2')

select ORDERNUMBER, ORDERNAME, CONCAT(ORDERNAME,' ',ORDERNAME) AS CONCATENATED_STRING FROM MYORDER

select ORDERNUMBER, ORDERNAME, CONCAT(ORDERNAME,' ',RAND()) AS CONCATENATED_STRING FROM MYORDER

--LEFT
SELECT ORDERNAME, LEFT(ORDERNAME,5) FROM MYORDER

--RIGHT
SELECT ORDERNAME, RIGHT(ORDERNAME,3) FROM MYORDER

--SUBSTRING
SELECT ORDERNAME, SUBSTRING(ORDERNAME,2,3) FROM MYORDER

--LOWER
SELECT ORDERNAME, LOWER(ORDERNAME) FROM MYORDER

--UPPER
SELECT ORDERNAME, UPPER(ORDERNAME) FROM MYORDER

--LENGTH
SELECT ORDERNAME, LEN(ORDERNAME) FROM MYORDER

--GIVE ME 1ST LETTER IN UPPER AND ALL OTHER IN LOWER
SELECT ORDERNAME, CONCAT(UPPER(LEFT(ORDERNAME,1)),LOWER(SUBSTRING(ORDERNAME,2,LEN(ORDERNAME)))) FROM MYORDER

--TRIM
SELECT '     BHUPESH      '
SELECT LEN('     BHUPESH      ')
SELECT LTRIM('     BHUPESH      ')
SELECT RTRIM('     BHUPESH      ')
SELECT LTRIM(RTRIM('     BHUPESH      ')) 