---------------------------DATE FUNCTIONS-----------------------------------------------

SELECT GETDATE()
SELECT GETDATE()-2

--DATEPART
SELECT DATEPART(YYYY, GETDATE())
SELECT DATEPART(MM, GETDATE())
SELECT DATEPART(DD, GETDATE())

--DATEADD
SELECT DATEADD(DAY,4,GETDATE())
SELECT DATEADD(DAY,4,'7/4/2015')
SELECT DATEADD(MONTH,4,GETDATE())
SELECT DATEADD(YEAR,4,GETDATE())

--DATEDIFF
SELECT * FROM [Production].[WorkOrder]
SELECT WORKORDERID, STARTDATE, ENDDATE, DATEDIFF(DAY,STARTDATE,ENDDATE) FROM [Production].[WorkOrder]

--GIVE ME 1ST DAY OF CURRENT MONTH
SELECT DATEADD(DAY, -(DATEPART(DAY,GETDATE())-1),GETDATE())


