----------------------------------JOINS-----------------------------------------------------

create table MYEMPLOYEE(EMPLOYEEID int, FIRSTNAME varchar(50), LASTNAME varchar(50))
select * from myemployee
insert into myemployee values(1,'Michael','Scott')
insert into myemployee values(2,'Pan','Beesly')
insert into myemployee values(3,'Dwight','Schrute')

create table MYSALARY(EMPLOYEEID int, SALARY float)
insert into MYSALARY values(1, 10000)
insert into MYSALARY values(2, 8000)
insert into MYSALARY values(3, 6000)
select * from MYSALARY

select * from myemployee
select * from MYSALARY

--INNER JOIN
SELECT * FROM MYEMPLOYEE A INNER JOIN MYSALARY B ON A.EMPLOYEEID=B.EMPLOYEEID

--LEFT OUTER JOIN
CREATE TABLE MYPHONE(EMPLOYEEID INT, PHONENUMBER INT)
INSERT INTO MYPHONE VALUES(1,1188455013)
INSERT INTO MYPHONE VALUES(2,1070234560)
INSERT INTO MYPHONE VALUES(4,1011111111)


SELECT * FROM MYPHONE
SELECT * FROM MYEMPLOYEE

SELECT * FROM MYEMPLOYEE A LEFT JOIN MYPHONE B ON A.EMPLOYEEID=B.EMPLOYEEID

SELECT A.FIRSTNAME, A.LASTNAME, B.PHONENUMBER FROM MYEMPLOYEE A LEFT JOIN MYPHONE B ON A.EMPLOYEEID=B.EMPLOYEEID

--RIGHT JOIN
SELECT * FROM MYEMPLOYEE A RIGHT JOIN MYPHONE B ON A.EMPLOYEEID=B.EMPLOYEEID

SELECT * FROM MYPHONE A RIGHT JOIN MYEMPLOYEE B ON A.EMPLOYEEID=B.EMPLOYEEID

--FULL OUTER JOIN

SELECT * FROM MYPHONE A FULL OUTER JOIN MYEMPLOYEE B ON A.EMPLOYEEID=B.EMPLOYEEID   

--CROSS JOIN
SELECT * FROM MYPHONE
SELECT * FROM MYEMPLOYEE
SELECT * FROM MYPHONE CROSS JOIN MYEMPLOYEE